// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psvxciccmshwdbuifkje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzdnhjaWNjbXNod2RidWlma2plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NDQwNjIsImV4cCI6MjA3NzMyMDA2Mn0.MFisJyS5U_X0xqn6vu4gatTNXokVbioFmcAx-tWoB8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});